# This is a basic workflow to help you get started with Actions

name: tarball build

# Controls when the workflow will run
on:
  # Triggers the workflow on a remote trigger
  workflow_dispatch:
    inputs:
      source:
        description: 'Source of event'
        required: false
        default: 'No source specified'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
#    container: fedora:36

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: update npm
        run: sudo npm install npm -g
      - name: install dependencies
        run: bash deps.sh
      - name: run a tarball build
        run: |
          bash tarball/tarball_build.sh
          mv WebCord_${{ env.tag }}_x86_64.tar.gz
      #- name: detection version for publishing
      #  run: echo "tag=$(bash get_latest_version_string.sh)" >> $GITHUB_ENV
      - name: Build on arm64
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: arm64
          uses: ubuntu20.04
          #githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            sudo npm install npm -g
            bash deps.sh
            bash tarball/tarball_build.sh
            mv WebCord_${{ env.tag }}_x86_64.tar.gz
      - name: Release file
        # You may pin to the exact commit or the version.
        # uses: djnicholson/release-action@e9a535b3eced09c460e07a84118fb74ae9b53236
        uses: djnicholson/release-action@v2.10
        with:
          # GitHub auth token
          token: ${{ secrets.GITHUB_TOKEN }}
          # Name of Release to add file to
          release-name: Release ${{ env.tag }}
          # Name of the tag for the release (will be associated with current branch)
          tag-name: ${{ env.tag }}
          # Name for the asset
          artifacts: "WebCord_*.tar.gz"

